# -*- coding: utf-8 -*-
"""seperate_data_from copy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bpChXLmu7xKwvq-puWtmNaPWwa6xV7zk
"""

import numpy as np
import pathlib
import cv2
import glob
import os

from google.colab import drive
drive.mount('/content/gdrive')

!tar -xvf "/content/gdrive/MyDrive/train_set.tar" -C "/content"

#setup
data_train = 'train_set'
data_dir_train = pathlib.Path(data_train)
annotation_exp_list_train =  list(data_dir_train.glob('*/*exp.npy'))
len(annotation_exp_list_train)

for a in annotation_exp_list_train:
	b = str(a)
	image_file_path = b.split('/')[-1].split('_')[0]+'.jpg'
	image = cv2.imread(os.path.join('train_set','images',image_file_path))
	label = str(np.int(np.load(a)))
	label_path = os.path.join('data_2_affectnet', label)
	if os.path.exists(label_path):
		cv2.imwrite(os.path.join(label_path, image_file_path), image)
	else:
		os.mkdir(label_path)
		cv2.imwrite(os.path.join(label_path, image_file_path), image)

len(list(pathlib.Path('/content/data_2_affectnet').glob('*/*')))

!zip -r /content/gdrive/MyDrive/output_file_name.zip /content/data_2_affectnet